# WE06 - Assignment (SVD)

## Subash Chandra Biswal ##
### U77884251 ###

### Import common packages

In [1]:
import pandas as pd
import numpy as np

np.random_seed = 1

### Load data

In [3]:
news = pd.read_csv('../Data/news.csv')

news.shape


(597, 5)

In [5]:
news.head(5)

TEXT  graphics  hockey  \
0  I have a few reprints left of chapters from my...         1       0   
1  gnuplot, etc. make it easy to plot real valued...         1       0   
2  Article-I.D.: snoopy.1pqlhnINN8k1 References: ...         1       0   
3  Hello, I am looking to add voice input capabil...         1       0   
4  I recently got a file describing a library of ...         1       0   

   medical newsgroup  
0        0  graphics  
1        0  graphics  
2        0  graphics  
3        0  graphics  
4        0  graphics

### Check for missing values

In [6]:
news[['TEXT']].isna().sum()

TEXT    0
dtype: int64

## Assign the input variable to X and the target variable to y

In [7]:
X = news['TEXT']

This is a multi-class classification problem. There are three categories we will predict:<br>
Whether a post is "graphics," "hockey," or "medical" related

In [8]:
y = news['newsgroup']
y.unique()

array(['graphics', 'hockey', 'medical'], dtype=object)

In [9]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
le.fit(y)
print(le.classes_)
y = le.transform(y)

y


['graphics' 'hockey' 'medical']


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

## Split the data

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [11]:
X_train.shape, y_train.shape

((417,), (417,))

In [12]:
X_test.shape, y_test.shape

((180,), (180,))

In [13]:
X_train.head(5)

589    In article < C5JDuo.K13@unx.sas.com> sasghm@th...
571    eulenbrg@carson.u.washington.edu (Julia Eulenb...
380    Well, since someone probably wanted to know, h...
52     In article < 1q7615INNmi@shelley.u.washington....
178    Hi. I'm writing a program to convert .dxf file...
Name: TEXT, dtype: object

In [14]:
y_train[:5]

array([2, 2, 1, 0, 0])

## Sklearn: Text preparation

For simplicity (and focus), we will not do any text cleaning or preprocessing. We will just use the raw text as input to the model. See the text mining fundamentals tutorial for more details on text cleaning and preprocessing.

In [15]:
#TfidfVectorizer includes pre-processing, tokenization, filtering stop words
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(stop_words='english', lowercase=True, token_pattern="[^\W\d_]+")

X_train = tfidf_vect.fit_transform(X_train)

**Notice in the previous step that we use `fit_transform` on TRAIN. When we transform the TEST data, we need to use `transform` only. This enables us to keep the number of columns (features) the same across the data sets. Otherwise, they WILL be different, and no model will work!**

In [16]:
# Perform the TfidfVectorizer transformation
# Be careful: We are using the train fit to transform the test data set. Otherwise, the test data 
# features will be very different and match the train set!!!

X_test = tfidf_vect.transform(X_test)


In [17]:
X_train.shape, X_test.shape

((417, 10140), (180, 10140))

In [18]:
# These data sets are "sparse matrix". We can't see them unless we convert using toarray()
X_train

<417x10140 sparse matrix of type '<class 'numpy.float64'>'
	with 30504 stored elements in Compressed Sparse Row format>

In [19]:
# These data sets are "sparse matrix". We can't see them unless we convert using toarray()
X_train.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## Latent Semantic Analysis (Singular Value Decomposition)

In [21]:
from sklearn.decomposition import TruncatedSVD

svd100 = TruncatedSVD(n_components=100, n_iter=10) #n_components is the number of topics, which should be less than the number of features

X_train100= svd100.fit_transform(X_train)
X_test100 = svd100.transform(X_test)

svd300 = TruncatedSVD(n_components=300, n_iter=10) #n_components is the number of topics, which should be less than the number of features

X_train300= svd300.fit_transform(X_train)
X_test300 = svd300.transform(X_test)

svd500 = TruncatedSVD(n_components=500, n_iter=10) #n_components is the number of topics, which should be less than the number of features

X_train500= svd500.fit_transform(X_train)
X_test500 = svd500.transform(X_test)


In [39]:
X_train100.shape, X_test100.shape

((417, 100), (180, 100))

## Random Forest

In [25]:
from sklearn.ensemble import RandomForestClassifier 

rnd_clf100 = RandomForestClassifier(n_estimators=100, max_leaf_nodes=16, n_jobs=-1) 
_ = rnd_clf100.fit(X_train100, y_train)

rnd_clf300 = RandomForestClassifier(n_estimators=100, max_leaf_nodes=16, n_jobs=-1) 
_ = rnd_clf300.fit(X_train300, y_train)

rnd_clf500 = RandomForestClassifier(n_estimators=100, max_leaf_nodes=16, n_jobs=-1) 
_ = rnd_clf500.fit(X_train500, y_train)

### Evaluating Model Performance

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
#Train accuracy - Not a good measure of model performance as we are using the same data set to train and test
y_pred_train100 = rnd_clf100.predict(X_train100)
acc100 = accuracy_score(y_train, y_pred_train100)
print(f"Train acc: {accuracy_score(y_train, y_pred_train100):.4f}")

y_pred_train300 = rnd_clf300.predict(X_train300)
acc300 = accuracy_score(y_train, y_pred_train300)
print(f"Train acc: {accuracy_score(y_train, y_pred_train300):.4f}")

y_pred_train500 = rnd_clf500.predict(X_train500)
acc500 = accuracy_score(y_train, y_pred_train500)
print(f"Train acc: {accuracy_score(y_train, y_pred_train500):.4f}")

Train acc: 0.9736
Train acc: 0.9808
Train acc: 0.9808


In [29]:
#Test accuracy
y_pred_test100 = rnd_clf100.predict(X_test100)
acc100 = accuracy_score(y_test, y_pred_test100)
print(f"Train acc: {accuracy_score(y_test, y_pred_test100):.4f}")

y_pred_test300 = rnd_clf300.predict(X_test300)
acc300 = accuracy_score(y_test, y_pred_test300)
print(f"Train acc: {accuracy_score(y_test, y_pred_test300):.4f}")

y_pred_test500 = rnd_clf500.predict(X_test500)
acc500 = accuracy_score(y_test, y_pred_test500)
print(f"Train acc: {accuracy_score(y_test, y_pred_test500):.4f}")

Train acc: 0.8778
Train acc: 0.9111
Train acc: 0.8833


In [32]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
print("\nSVD 100\n")
print(confusion_matrix(y_test, y_pred_test100))
print("\nSVD 300\n")
print(confusion_matrix(y_test, y_pred_test300))
print("\nSVD 500\n")
print(confusion_matrix(y_test, y_pred_test500))


SVD 100

[[51  0  6]
 [ 1 55  5]
 [ 7  3 52]]

SVD 300

[[51  0  6]
 [ 0 60  1]
 [ 7  2 53]]

SVD 500

[[47  0 10]
 [ 0 58  3]
 [ 4  4 54]]


## Stochastic Gradient Descent Classifier

In [33]:
from sklearn.linear_model import SGDClassifier

sgd_clf100 = SGDClassifier(max_iter=100)
_ = sgd_clf100.fit(X_train100, y_train)

sgd_clf300 = SGDClassifier(max_iter=100)
_ = sgd_clf300.fit(X_train300, y_train)

sgd_clf500 = SGDClassifier(max_iter=100)
_ = sgd_clf500.fit(X_train500, y_train)

### Evaluating Model Performance

In [34]:
#Train accuracy
y_pred_train100 = sgd_clf100.predict(X_train100)
print(f"Train acc: {accuracy_score(y_train, y_pred_train100):.4f}")

y_pred_train300 = sgd_clf300.predict(X_train300)
print(f"Train acc: {accuracy_score(y_train, y_pred_train300):.4f}")

y_pred_train500 = sgd_clf500.predict(X_train500)
print(f"Train acc: {accuracy_score(y_train, y_pred_train500):.4f}")

Train acc: 0.9784
Train acc: 0.9952
Train acc: 0.9952


In [35]:
#Test accuracy
y_pred_test100 = sgd_clf100.predict(X_test100)
print(f"Train acc: {accuracy_score(y_train, y_pred_train100):.4f}")

y_pred_test300 = sgd_clf300.predict(X_test300)
print(f"Train acc: {accuracy_score(y_train, y_pred_train300):.4f}")

y_pred_test500 = sgd_clf500.predict(X_test500)
print(f"Train acc: {accuracy_score(y_train, y_pred_train500):.4f}")

Train acc: 0.9784
Train acc: 0.9952
Train acc: 0.9952


In [38]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix

print("\nSVD 100\n")
print(confusion_matrix(y_test, y_pred_test100))

print("\nSVD 300\n")
print(confusion_matrix(y_test, y_pred_test300))

print("\nSVD 500\n")
print(confusion_matrix(y_test, y_pred_test500))


SVD 100

[[49  0  8]
 [ 1 52  8]
 [ 2  1 59]]

SVD 300

[[52  0  5]
 [ 1 56  4]
 [ 3  2 57]]

SVD 500

[[50  0  7]
 [ 0 59  2]
 [ 2  2 58]]


## Analysis ##

It can be observed that the n_components of SVD which defines the number of components (fathures) plays an important role in the performance of models.

Since this should be less than number of observations, n_components of 300 performs best for both Random Forest and SGD classifies. This n_components can not be too small such as 100 which performed worst for this dataset.

SVD is used to use matrix factorization of components to make it linear and thus reduce the dimensions. This method is applicable where we have a lot of components to consider such as image data or text data (unstructured/semistructured).